language: cpp
compiler: g++
sudo: required
dist: trusty

branches:
  only:
  - master

addons:
  coverity_scan:
    project:
      name: theikeofficial/GiA
    notification_email: ajzenhamernikola@gmail.com
    build_command_prepend: "cov-configure --gcc && qmake GiA.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug && make qmake_all"
    build_command: "make VERBOSE=1"
    branch_pattern: coverity_scan
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

env:
  global:
  - secure: LgS+vn1QArEAPjVVThOEWa2EsnZtnbWNEqu2HbiIlsiBSEnTWNpZDCP4LUGe4ENv4GN7okXNmGQMKhRxviMpnrafWN+pX8YI2u6gw0M54o8zMMyxdEiR7m60F8NQVLHEVgAY+GDzfZQQ258OjdXmnoRfIkF10PNX1bYlsyy8sjp5aNvTUocBTXNHcwAWVCXzUHJrgFYjLVdM8BgjffK8lAi3F+WAk3AnmeAJcQcJ1FvzYV6FAZu7iP7oJ8tblm9xmpIFNjzFltJ4arvSy1FRwgoKfXTqau6wBTK+EkOItoeV9x6fkJoIFeUA2UuL5bW9UWcWrCQdVFt5NpJ0T/+OtBWzxCJ4k49S6ZdCCocU6xlck6Z6vZvJjQjnx2TFxOadh3HUXJJsiGO+ublLf4RKE/qTs3XZkCpw7jNf6/9Wf+zMb+8bCSOOkkg5UTI9nZ9eE5+AaVLGi+b67sn6QwZ6CLdmwtK6JcMpctSXVH0WUP5a/gh3kGA8FO4v9eRoTTRN+Wwr472fqCGwONpBIja4Whwjqj+qYdjLwP5GDtJtlVExVSLTvOdKoDjsdn/caemyeKL6E3VekCoXd2UI5R16H3GAvMsXmXbYAK1Llg90X3dms6Rte+OvK/rySH7JnTu70KvdhE6o0GHbfZcGm8wz+U5jpMGO5hFkRfRcF8V1CZ8=

before_install:
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
- sudo apt-get update -qq

install: export CXX="g++-7"

script:
- if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]]; then echo "Don't build on coverty_scan branch."; exit 0; fi
- which qmake
- which make
- which g++
- g++ -version
- qmake GiA.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
- make qmake_all
- make
